trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '14.x'
  displayName: 'Install Node.js'

- script: |
    npm install
    npm pack
  displayName: 'Pack User Management Backend'

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(System.DefaultWorkingDirectory)'
    artifact: 'user-management-backend'

- task: NpmAuthenticate@0
  inputs:
    workingFile: .npmrc

- task: Npm@1
  displayName: 'Publish Npm Package to Azure Artifacts'
  inputs:
    command: 'publish'
    publishRegistry: 'useFeed'
    publishFeed: 'EpisodeDetector/exalent-user-management-backend'
    workingDirectory: '$(System.DefaultWorkingDirectory)'
